### ISSUE TITLE
Knowing which icons are genuine

### ISSUE THREAD

**Issue by letalvoj** [ivebencrazy/favioli#29]
I'd love to know which icons are genuine simply by adding some pixel size (dot/underscore line) to the icon. 

Does this idea make sense to you aswell?

**Comment by ivebencrazy** [comment]
I'm unsure what this means.  Like to know whether favioli is creating a favicon vs whether the native favicon is showing?

**Comment by ivebencrazy** [comment]
That is definitely something we could add without too much difficulty.  I'm mostly focusing on bugs at the moment, because having a favicon show/not show at the wrong time is the worst.  However, I think I should be able to get around to adding a setting for this feature over the weekend. Thanks for the suggestion!

**Comment by ivebencrazy** [comment]
Hihi!  Look for this in the next release!

Might be a little more time, because I want to add testing before 1.1.0, but should be relatively soon.
