### ISSUE TITLE
Firefox version 

### ISSUE THREAD

**Issue by JBertaux** [ivebencrazy/favioli#34]
Is there a Firefox version planed ?

Thanks !

**Comment by Riajyuu** [comment]
@ivebencrazy just a question here? Will you work on UI a bit so that it fits Firefox for Android?

**Comment by ivebencrazy** [comment]
I don't have an android phone, so I probably won't want to put in the effort/money to do this personally.  Once I do have a FF version (I think I'll have time this weekend?), I'm def open to looking over PRs, though. I'll try to make my README more dev-oriented so it would be easier to help develop.

**Comment by ivebencrazy** [comment]
Having some issues with the Options page, due to FF not supporting web components as I am using them, and web component polyfills I've found not really doing what I need.

For the time being, I have added a contentScript-only version to [Firefox Add-ons Store](https://addons.mozilla.org/en-US/firefox/addon/favioli/).  Meaning this version will only support adding emoji favicons to websites that don't have a favicon (aka no configurable options page).  I wanted to post that link here in case this functionality is good enough for your use-case, because I'll have to re-work the ui a bit to make the options page work, and I might not be done this weekend. 

I don't want to have an official non-experimental release until I can make sure everything is working as I want it to.  But hopefully this is alright to use in the meantime.  😄 

https://addons.mozilla.org/en-US/firefox/addon/favioli/

**Comment by Riajyuu** [comment]
@ivebencrazy 
just test out a bit: the answer shall be negative.
![](https://i.imgur.com/32P8ypX.png)

The last tab in awesome screen doesn't have favicon from webpage. But as you can see nothing happened after I finish loading it.

**Comment by ivebencrazy** [comment]
Hmm that's disappointing...  I'm also realizing that on this desktop FF version, I have to refresh the first time it loads for the favicon to update.  I need to figure out why that is happening on this Firefox version, and I wonder if it might just be that on mobile as well.  But if it's not that, I'm guessing that it's expecting some more information in about the favicon in the html.  Hopefully the api allows us to edit favicon on mobile though; I haven't tried that at all.

I'm going on vacation on Tuesday, and I'm trying to get the FF desktop version done before then. I'll take a closer look at mobile version when I get back end of next week, though.  Probably will make a new issue to keep track of that, though.  I would like this thread to be about FF desktop only if that's ok, so we can separate the issues, and so I don't blow up JBertaux's notification anymore haha 👍

**Comment by ivebencrazy** [comment]
Full-featured Firefox build will be up later today. :+1:
https://addons.mozilla.org/en-US/firefox/addon/favioli/

**Comment by Riajyuu** [comment]
@ivebencrazy I think you just need to reopen this.
As my test, the replacement doesn't happen on first load. It only comes when you load a domain for a second time.
Or shall I open a new issue?

**Comment by ivebencrazy** [comment]
Please create a new issue for this.  Although I've seen the issue you're referring to, and I'm not certain I can fix this without refreshing the page or affecting page load.  Favioli is correctly setting the favicon correctly, but firefox isn't re-indexing it on that change.
